apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spring-boot-service
  title: SportsTix Spring Boot Microservice
  description: Golden Path template for creating a new Spring Boot 3.3 microservice with PostgreSQL, Kafka, and Kubernetes manifests
  tags:
    - java
    - spring-boot
    - recommended
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Information
      required:
        - serviceName
        - description
        - port
      properties:
        serviceName:
          title: Service Name
          type: string
          description: Name of the microservice (e.g., notification)
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Brief description of the service
        port:
          title: Port
          type: integer
          description: HTTP port number (8087+)
          default: 8087
          minimum: 8087
          maximum: 8099

    - title: Features
      properties:
        hasDatabase:
          title: PostgreSQL Database
          type: boolean
          default: true
        hasKafka:
          title: Kafka Integration
          type: boolean
          default: true
        hasRedis:
          title: Redis Cache
          type: boolean
          default: false
        hasWebSocket:
          title: WebSocket Support
          type: boolean
          default: false
        useJooq:
          title: jOOQ (Hot Path)
          type: boolean
          default: false
          description: Enable jOOQ for high-concurrency paths

    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          serviceName: ${{ parameters.serviceName }}
          description: ${{ parameters.description }}
          port: ${{ parameters.port }}
          hasDatabase: ${{ parameters.hasDatabase }}
          hasKafka: ${{ parameters.hasKafka }}
          hasRedis: ${{ parameters.hasRedis }}
          hasWebSocket: ${{ parameters.hasWebSocket }}
          useJooq: ${{ parameters.useJooq }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts:
          - github.com
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Service Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
