apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: sportstix
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.38.1
    helm:
      releaseName: argo-rollouts
      values: |
        controller:
          replicas: 1
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: observability
        dashboard:
          enabled: true
          readonly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
