apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: sportstix
  source:
    repoURL: https://charts.chaos-mesh.org
    chart: chaos-mesh
    targetRevision: 2.7.1
    helm:
      releaseName: chaos-mesh
      values: |
        chaosDaemon:
          runtime: containerd
          socketPath: /run/containerd/containerd.sock
        dashboard:
          securityMode: true
        controllerManager:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
