apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: sportstix
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.12.1
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        webhook:
          port: 9443
        certController:
          requeueInterval: 5m
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
